# Generated by Django 2.2 on 2021-09-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends_app', '0002_favoritegame'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='growth',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
