# Generated by Django 2.2 on 2021-09-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends_app', '0003_game_growth'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bgg_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='growth_rank',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='play_rank',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='year_published',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='growth',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(default='Game 0', max_length=255),
        ),
    ]
