# Generated by Django 2.2 on 2021-09-09 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trends_app', '0004_auto_20210908_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyplay',
            name='game',
        ),
        migrations.AddField(
            model_name='monthlyplay',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_play', to='trends_app.Game'),
            preserve_default=False,
        ),
    ]
