# Generated by Django 2.2 on 2021-09-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends_app', '0005_auto_20210908_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyplay',
            name='month',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyplay',
            name='plays',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyplay',
            name='year',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
