# Generated by Django 2.2 on 2021-09-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends_app', '0006_auto_20210908_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='plays',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
