# Generated by Django 2.2 on 2021-09-10 01:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trends_app', '0007_game_plays'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='fav_users',
            field=models.ManyToManyField(related_name='fav_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FavoriteGame',
        ),
    ]
