# Generated by Django 2.2 on 2021-09-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends_app', '0008_auto_20210909_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_pic',
            field=models.CharField(default='', max_length=255),
        ),
    ]
