# Generated by Django 2.2 on 2021-09-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends_app', '0010_auto_20210911_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyplay',
            name='h',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
