# Generated by Django 2.2 on 2021-09-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends_app', '0011_monthlyplay_h'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='h',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='h_rank',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
