# Generated by Django 2.2 on 2021-09-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends_app', '0012_auto_20210911_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='year_published',
            field=models.SmallIntegerField(default=0),
        ),
    ]
