# Generated by Django 2.2 on 2021-09-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends_app', '0013_auto_20210912_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='h_growth',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='h_growth_rank',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
