# Generated by Django 2.2 on 2021-09-19 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends_app', '0014_auto_20210916_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='growth',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='h_growth',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='plays',
            field=models.FloatField(default=0),
        ),
    ]
